name_translation = {
    "Donald Ackerman": "Donald Ackerman",
    "Charles Acton": "Bud Acton",
    "Daniel Anderson": "Dan Anderson",
    "Mitchell Anderson": "Mitch Anderson",
    "Nate Archibald": "Tiny Archibald",
    "Paul Armstrong": "Curly Armstrong",
    "Omer Asik": "Omer Ask",
    "Richard Atha": "Dick Atha",
    "Alvin Attles": "Al Attles",
    "Ike Austin": "Isaac Austin",
    "John Austin": "Johnny Austin",
    "William Averitt": "Bird Averitt",
    "Wade Baldwin IV": "Wade Baldwin",
    "Stephen Bardo": "Steve Bardo",
    "Thomas Barr": "Moe Barr",
    "Billyray Bates": "Billy Ray Bates",
    "William Bell": "Whitey Bell",
    "Arlen Bockhorn": "Bucky Bockhorn",
    "George H. Bon Salle": "George Bon Salle",
    "Costic Borsavage": "",
    "Brian Bowen II": "",
    "Fred Boyd": "",
    "Frank Brian": "",
    "Audley Brindley": "",
    "David Britton": "",
    "Darrell Brown": "",
    "Emmette Bryant": "",
    "Walter Budko": "",
    "Reggie Bullock Jr.": "",
    "Luther Burden": "",
    "Brian Butch": "",
    "Da'Sean Butler": "",
    "John Butler Jr.": "",
    "Mike Bytzura": "",
    "Jaylen Clark": "",
    "John Clemens": "",
    "Marion Cluggish": "",
    "John Cox": "",
    "Mitchell Creek": "",
    "Jeffrey Crompton": "",
    "Francis Crossin": "",
    "Lou Dampier": "",
    "Henry Darcey": "",
    "Double D Davis": "",
    "Edward Davis": "",
    "James Davis": "",
    "Michael Davis": "",
    "Walter Devlin": "",
    "John Dillon": "",
    "Lloyd Dove": "",
    "Jeff Dowtin Jr.": "",
    "Thomas Eddleman": "",
    "Kent Edelin": "",
    "Vincent Edwards": "",
    "Eddie Ehlers": "",
    "Dick Eichhorst": "",
    "Alexander Ellis": "",
    "Wayne Englestad": "",
    "Jojo English": "",
    "Vitor Faverani": "",
    "Bill Fenley": "",
    "Ike Fontaine": "",
    "Michael Frazier II": "",
    "Melvin Frazier Jr.": "",
    "World Free": "",
    "Billy Gabor": "",
    "Tony Gaffney": "",
    "Elmer R. Gainer": "",
    "Eldo Garrett": "",
    "Kiwane Garris": "",
    "Ward Gibson": "",
    "Harry Giles III": "",
    "Gene Gillette": "",
    "Norman Glick": "",
    "Wilfred Goodwin": "",
    "Ronnie Grandison": "",
    "AJ Green": "",
    "Tommy Green": "",
    "David Greenwood": "",
    "George Grimshaw": "",
    "Petur Gudmundsson": "",
    "Ha Seung-jin": "",
    "Bob Hahn": "",
    "PJ Hairston": "",
    "Chuck Halbert": "",
    "Harvey Halbrook": "",
    "Roylee Hamilton": "",
    "AJ Hammons": "",
    "Kenny Hasbrouck": "",
    "Joey Hassett": "",
    "Robert Hawkins": "",
    "John W. Hazen": "",
    "Garfield Heard": "",
    "Clarence Hermsen": "",
    "Sidney Hertzberg": "",
    "Matthew Hickey": "",
    "JJ Hickson": "",
    "Herbert Hill": "",
    "Adolph Hoefer": "",
    "Paul 'The Bear' Hoffman": "",
    "Alvin Holt": "",
    "Caleb Homesley": "",
    "Wilmer Hosket": "",
    "Rod Hundley": "",
    "RJ Hunter": "",
    "Vincent Hunter": "",
    "Joel Ingram": "",
    "GG Jackson": "",
    "Lucious Jackson": "",
    "Winfred Jacobs": "",
    "Curtis Jerrells": "",
    "Pooh Jeter": "",
    "BJ Johnson": "",
    "Charlie Johnson": "",
    "Lynbert Johnson": "",
    "Charles R. Jones": "",
    "Wallace Jones": "",
    "Perry Jones III": "",
    "Edwin Kachan": "",
    "Michael Kearns": "",
    "Gerard Kelly": "",
    "Eugene Kennedy": "",
    "William Kennedy": "",
    "Bill Kenville": "",
    "Johnny Kerr": "",
    "Ernie Killum": "",
    "Maury King": "",
    "Herm Klotz": "",
    "Kevin Knox II": "",
    "Tom Kron": "",
    "Charles Kupec": "",
    "Ibrahim Kutluay": "",
    "Ed Lawrence": "",
    "Dennis Layton": "",
    "Emanuel Leaks": "",
    "Russell Lee": "",
    "Bob Leonard": "",
    "Lafayette Lever": "",
    "Fred Lewis": "",
    "Justin Lewis": "",
    "Robert Lock": "",
    "Johnny Logan": "",
    "Chuck Lowery": "",
    "Francis Mahoney": "",
    "Marcus Mann": "",
    "Richard Manning": "",
    "Peter Maravich": "",
    "Eric Marsh": "",
    "Donald Martin": "",
    "Larue Martin": "",
    "Mo Martin": "",
    "Ronald Martin": "",
    "Roger Mason Jr.": "",
    "DJ Mbenga": "",
    "Ted 'Hound Dog' McClain": "",
    "Paul McConnell": "",
    "KJ McDaniels": "",
    "Bill McGill": "",
    "Horace McKinney": "",
    "Mccoy McLemore": "",
    "Mal McMullan": "",
    "Slava Medvedenko": "",
    "Don Meineke": "",
    "Zigmund Mihalik": "",
    "CJ Miles": "",
    "Elmo Morgenthaler": "",
    "Marcus Morris Sr.": "",
    "Dwight Morrison": "",
    "Flip Murray": "",
    "Makhtar N'diaye": "",
    "Makhtar N'diaye": "",
    "Mamadou N'diaye": "",
    "Fred Nagy": "",
    "Charles Nash": "",
    "Hamady Ndiaye": "",
    "Boniface Ndong": "",
    "John Niemiera": "",
    "Robert Nordmann": "",
    "Miles Norris": "",
    "Zach Norvell Jr.": "",
    "Buckshot O'Brien": "",
    "JJ O'Brien": "",
    "Johnny O'Bryant III": "",
    "Francis O'Grady": "",
    "Carlos Ogden": "",
    "Johnny Oldham": "",
    "Enoch Olsen": "",
    "James Owens": "",
    "John Palmer": "",
    "Estes Parham": "",
    "Medford Park": "",
    "George A. Pastushok": "",
    "Tommy Patterson": "",
    "Mike Phelps": "",
    "Tarik Phillip": "",
    "Charlie Pittman": "",
    "Tibor Pleiss": "",
    "Craig Porter": "",
    "AJ Price": "",
    "Luke Rackley": "",
    "Jamesearl Ray": "",
    "Joseph Reiser": "",
    "Rob Rensberger": "",
    "Cam Reynolds": "",
    "Sir'Jabari Rice": "",
    "Norman Richardson": "",
    "Goebel Ritter": "",
    "Cliff T. Robinson": "",
    "Magnum Rolle": "",
    "Robert Rose": "",
    "Alexander Rosenberg": "",
    "Jermaine Samuels Jr.": "",
    "Thomas Sanders": "",
    "Frank Saul": "",
    "Dewayne Scales": "",
    "Dan Schayes": "",
    "Freddie Scolari": "",
    "Trevon Scott": "",
    "Ken Sears": "",
    "Charlie Share": "",
    "Edmund Sherod": "",
    "Charlie Shipp": "",
    "Diamon Simpson": "",
    "Mckinley Singleton": "",
    "Talvin Skinner": "",
    "Donald Smith": "",
    "JR Smith": "",
    "Labradford Smith": "",
    "Sammy Smith": "",
    "George Sobek": "",
    "Isaac Stallworth": "",
    "DJ Stephens": "",
    "DJ Stewart": "",
    "DJ Strawberry": "",
    "Michael Sweetney": "",
    "Wallace Sydnor": "",
    "Sid Tannenbaum": "",
    "Jeffery Taylor": "",
    "Roland Taylor": "",
    "Howard Tidrick": "",
    "Xavier Tillman": "",
    "Marko Todorovich": "",
    "William Towery": "",
    "Mel Turpin": "",
    "Robert Vaden": "",
    "Ron Valentine": "",
    "Butch Van Breda Kolff": "",
    "Jan Van Breda Kolff": "",
    "Log Vander Velden": "",
    "Charles Vaughn": "",
    "Peter Verhoeven": "",
    "Luca Vildoza": "",
    "MJ Walker": "",
    "Michael Wallace": "",
    "Rabbit Walthour": "",
    "Derrick Walton Jr.": "",
    "Johnny Warren": "",
    "Dwayne Washington": "",
    "Clar. Weatherspoon": "",
    "Forest Weber": "",
    "Lucian Whitaker": "",
    "DJ White": "",
    "Jojo White": "",
    "Terrico White": "",
    "Andrew White III": "",
    "Charles Whitney": "",
    "Eddielee Wilkins": "",
    "Arthur Williams": "",
    "Don Williams": "",
    "Samuel Williams": "",
    "Robert Williams III": "",
    "Matt Williams Jr.": "",
    "Mike Wilson": "",
    "Thomas Wilson": "",
    "Kenny Wooten": "",
    "Robert Zawoluk": "",
    "Hank Zeller": "",
    "Wang Zhi-zhi": "",
}
